### ISSUE TITLE
ElementClickInterceptedException at the end

### ISSUE THREAD

**Issue by GilDev** [ItCameFr0mMars/RedditBotMaker#4]
After running the script and completing the Captcha, I got the following log with a crash:

I’m on macOS 12.1 with Python 3.9.10.

```
====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
There is no [mac64] chromedriver for browser 99.0.4844 in cache
Trying to download new driver from https://chromedriver.storage.googleapis.com/99.0.4844.51/chromedriver_mac64.zip
Driver has been saved in cache [/Users/gildev/.wdm/drivers/chromedriver/mac64/99.0.4844.51]
/Users/gildev/RedditBotMaker/namesforreddit.py:23: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install()) # USES CHROMEDRIVERMANAGER TO AUTO UPDATE CHROMEDRIVER
/Users/gildev/RedditBotMaker/namesforreddit.py:32: DeprecationWarning: find_element_by_class_name is deprecated. Please use find_element(by=By.CLASS_NAME, value=name) instead
  temp = driver.find_element_by_class_name("firstHeading").text
/Users/gildev/RedditBotMaker/namesforreddit.py:59: DeprecationWarning: find_element_by_class_name is deprecated. Please use find_element(by=By.CLASS_NAME, value=name) instead
  email = driver.find_element_by_class_name("mailtext").get_attribute("value")
jer39464@yuoia.com
/Users/gildev/RedditBotMaker/namesforreddit.py:62: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_id('regEmail').send_keys(email)
/Users/gildev/RedditBotMaker/namesforreddit.py:64: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//button[contains(text(),'Continue')]").click()
/Users/gildev/RedditBotMaker/namesforreddit.py:66: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_id('regUsername').send_keys(finalName)
/Users/gildev/RedditBotMaker/namesforreddit.py:67: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_id('regPassword').send_keys(password)
continue when you have finish the captcha
/Users/gildev/RedditBotMaker/namesforreddit.py:70: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//button[@class='AnimatedForm__submitButton SignupButton']").click()
/Users/gildev/RedditBotMaker/namesforreddit.py:72: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//button[@class='AnimatedForm__submitButton SubscribeButton']").click()
/Users/gildev/RedditBotMaker/namesforreddit.py:76: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//input[@class='fancybutton newbutton allow']").click()
/Users/gildev/RedditBotMaker/namesforreddit.py:80: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//a[contains(text(), 'Reddit')]").click()
/Users/gildev/RedditBotMaker/namesforreddit.py:82: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//body").click()
/Users/gildev/RedditBotMaker/namesforreddit.py:87: DeprecationWarning: find_element_by_class_name is deprecated. Please use find_element(by=By.CLASS_NAME, value=name) instead
  driver.find_element_by_class_name("btn-14").click()
Traceback (most recent call last):
  File "/Users/gildev/RedditBotMaker/namesforreddit.py", line 87, in <module>
    driver.find_element_by_class_name("btn-14").click()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <td class="btn-14" bgcolor="#0079D3" style="font-size:14px;line-height:18px;color:#ffffff;font-family:Helvetica, Arial, sans-serif;text-align:center;">...</td> is not clickable at point (601, 1238). Other element would receive the click: <iframe id="aswift_6" name="aswift_6" style="width: 728px !important; height: 90px !important; display: block; margin: 0px auto;" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" width="728" height="90" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" src="https://googleads.g.doubleclick.net/pagead/html/r20220330/r20110914/zrt_lookup.html?fsb=1#RS-0-&amp;adk=1812271801&amp;client=ca-pub-4868759087006546&amp;fa=1&amp;ifi=7&amp;uci=a!7&amp;btvi=2&amp;xpc=h4CJy3XYLz&amp;p=https%3A//10minutemail.org" data-google-container-id="a!7" data-google-query-id="CMrvr7Sa-_YCFf5qFQgdbGgBBA" data-load-complete="true"></iframe>
  (Session info: chrome=99.0.4844.84)
Stacktrace:
0   chromedriver                        0x000000010767c159 chromedriver + 5120345
1   chromedriver                        0x0000000107609b13 chromedriver + 4651795
2   chromedriver                        0x00000001071f9e68 chromedriver + 392808
3   chromedriver                        0x00000001072367e8 chromedriver + 641000
4   chromedriver                        0x0000000107234288 chromedriver + 631432
5   chromedriver                        0x0000000107231a04 chromedriver + 621060
6   chromedriver                        0x000000010723078c chromedriver + 616332
7   chromedriver                        0x0000000107224109 chromedriver + 565513
8   chromedriver                        0x000000010724cb42 chromedriver + 731970
9   chromedriver                        0x00000001072239b5 chromedriver + 563637
10  chromedriver                        0x000000010724cc4e chromedriver + 732238
11  chromedriver                        0x000000010725f637 chromedriver + 808503
12  chromedriver                        0x000000010724ca33 chromedriver + 731699
13  chromedriver                        0x00000001072225dd chromedriver + 558557
14  chromedriver                        0x00000001072234f5 chromedriver + 562421
15  chromedriver                        0x000000010763938d chromedriver + 4846477
16  chromedriver                        0x000000010765321c chromedriver + 4952604
17  chromedriver                        0x0000000107658a12 chromedriver + 4975122
18  chromedriver                        0x0000000107653b4a chromedriver + 4954954
19  chromedriver                        0x000000010762e5b0 chromedriver + 4801968
20  chromedriver                        0x000000010766df78 chromedriver + 5062520
21  chromedriver                        0x000000010766e0ff chromedriver + 5062911
22  chromedriver                        0x0000000107683545 chromedriver + 5150021
23  libsystem_pthread.dylib             0x00007ff80369a4f4 _pthread_start + 125
24  libsystem_pthread.dylib             0x00007ff80369600f thread_start + 15
```

**Comment by ItCameFr0mMars** [comment]
it seems that everything js going well until the email verification, try running the script against and see if it still makes the error. also are you using a vpn?

**Comment by ItCameFr0mMars** [comment]
increasing the wait on line 86 may also help

**Comment by ItCameFr0mMars** [comment]
I have updated the script to no longer use the pooblic place thing, and also I have implemented waits so the program is more optimized
